### ISSUE TITLE
About new-released version 1.1.1

### ISSUE THREAD

**Issue by libook** [aliyun/aliyun-log-nodejs-sdk#10]
Hi, I found that you have released v1.1.1 on npm 2 months ago. And previous release version is 1.2.0. It seems that you have added a new feature about supporting STS Token in PR #9. May I ask why did you bump version to 1.1.1; instead of 1.2.1 or 1.3.0? Developers with v1.2.x will miss this new feature.

**Comment by libook** [comment]
@JacksonTian

**Comment by JacksonTian** [comment]
No. After 1.1.1 will has this feature also. There is no break changes, so I released the 1.1.1.

**Comment by libook** [comment]
@JacksonTian Thanks for your replying.
Please check the "versions" tab on npm https://www.npmjs.com/package/@alicloud/log
There is 1.2.0 version. And some one is using v1.2.0 .
