### ISSUE TITLE
STS 认证方式支持

### ISSUE THREAD

**Issue by sang4lv** [aliyun/aliyun-log-nodejs-sdk#8]
STS token 可以通过头部的 `x-acs-security-token` 来支持，但目前在 options 里传递 headers 字段会因为 [L106](https://github.com/aliyun/aliyun-log-nodejs-sdk/blob/master/lib/client.js#L106) 的 `Object.assign` 浅拷贝导致整个 headers 被替换（包含请求的签名）。

有两个方法支持 STS：

1. 把 options 的浅拷贝替换成深拷贝方式，继续传递头部字段；或
2. 在 config 里新增一个 securityToken 字段，在 `_request` 方法里判断是否需要加上。

**Comment by JacksonTian** [comment]
fixed in #9
